import { makeStyles } from "@material-ui/core/styles";

export default makeStyles((theme) => ({
  toolbar: theme.mixins.toolbar,
  mainPage: { flexGrow: 1, overflowX: "hidden", overflowY: "hidden" },
  content: {
    flexGrow: 1,
    backgroundColor: theme.palette.background.default,
    padding: theme.spacing(20),
    paddingTop: theme.spacing(2),
  },
  hero: {
    flexDirection: "column",
    height: "90vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: theme.spacing(20),
    backgroundColor: "white",
  },
  heroHeader: {
    textAlign: "center",
    color: "#001524",
    fontSize: 72,
    fontFamily: "Raleway",
    fontWeight: "800",
    letterSpacing: -2,
    lineHeight: 0.8,
    wordSpacing: 4,
    width: 660,
    paddingBottom: 8,
  },
  heroDesc: {
    textAlign: "center",
    color: "#001524",
    fontSize: 24,
    fontFamily: "Raleway",
    paddingBottom: 28,
    width: 584,
  },
  contentHeader: {
    textAlign: "center",
    color: "#001524",
    fontSize: 40,
    fontFamily: "Raleway",
    fontWeight: "bolder",
    paddingTop: theme.spacing(5),
    backgroundColor: "#EEEEEE",
    margin: "0 !important",
  },
  contentFeatured: {
    gap: 15,
    padding: theme.spacing(5),
    paddingTop: theme.spacing(4),
    paddingBottom: theme.spacing(7),
    backgroundColor: "#EEEEEE",
  },
  root: {
    flexGrow: 1,
  },
  searchs: {
    justifyContent: "center",
    display: "flex",
  },
  searchb: {
    backgroundColor: "white",
    height: "80%",
    width: "60%",
    padding: "15px",
    borderRadius: "10px",
    border: "1px solid #001524",
  },
  booksHeader: {
    textAlign: "center",
    color: "#001524",
    fontSize: 40,
    fontFamily: "Raleway",
    fontWeight: "bolder",
    paddingTop: theme.spacing(10),
  },
  booksDesc: {
    textAlign: "center",
    color: "#001524",
    fontSize: 20,
    paddingBottom: theme.spacing(2),
    fontFamily: "Raleway",
  },
  "@media (max-width: 1600px)": {
    hero: {
      flexDirection: "column",
      height: "100vh",
      gap: 0,
      paddingTop: 0,
      justifyContent: "center",
    },
    heroHeader: {
      textAlign: "center",
      color: "#001524",
      fontSize: 60,
      fontFamily: "Raleway",
      fontWeight: "800",
      letterSpacing: -2,
      lineHeight: 1,
      wordSpacing: 4,
      width: 600,
      paddingBottom: 8,
    },
    heroDesc: {
      textAlign: "center",
      color: "#001524",
      fontSize: 24,
      fontFamily: "Raleway",
      paddingBottom: 28,
      width: 584,
    },
    searchs: {
      justifyContent: "center",
    },
    heroImg: {
      height: 480,
    },
    content: {
      padding: 8,
    },
  },
  "@media (max-width: 700px)": {
    hero: {
      flexDirection: "column",
      height: "100vh",
      gap: 20,
      paddingTop: 0,
    },
    heroCont: {
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      flexDirection: "column",
    },
    heroHeader: {
      textAlign: "center",
      color: "#001524",
      fontSize: 28,
      fontFamily: "Raleway",
      fontWeight: "800",
      letterSpacing: -2,
      lineHeight: 1,
      wordSpacing: 4,
      width: 332,
      paddingBottom: 8,
    },
    heroDesc: {
      textAlign: "center",
      color: "#001524",
      fontSize: 12,
      fontFamily: "Raleway",
      paddingBottom: 28,
      width: 332,
    },
    contentHeader: {
      fontSize: 28,
    },
    booksDesc: {
      fontSize: 12,
    },
    booksHeader: {
      fontSize: 28,
    },
    searchs: {
      justifyContent: "center",
      display: "flex",
    },
    searchb: {
      height: "80%",
      width: "100%",
    },
    heroImg: {
      height: 280,
    },
    content: {
      padding: 0,
    },
    contentFeatured: {
      gap: 0,
      padding: theme.spacing(0),
      paddingTop: theme.spacing(4),
      paddingBottom: theme.spacing(7),
    },
  },
}));
