import { makeStyles } from "@material-ui/core/styles";

export default makeStyles((theme) => ({
  toolbar: theme.mixins.toolbar,
  mainPage: { flexGrow: 1, overflowX: "hidden", overflowY: "hidden" },
  content: {
    flexGrow: 1,
    backgroundColor: theme.palette.background.default,
    padding: theme.spacing(20),
    paddingTop: theme.spacing(2),
  },
  hero: {
    height: "80vh",
    display: "flex",
    justifyContent: "space-around",
    alignItems: "center",
    padding: theme.spacing(20),
    gap: 20,
    backgroundColor: "white",
  },
  heroHeader: {
    textAlign: "left ",
    color: "#001524",
    fontSize: 72,
    fontFamily: "Raleway",
    fontWeight: "800",
    letterSpacing: -2,
    lineHeight: 0.8,
    wordSpacing: 4,
    width: 600,
    paddingBottom: 8,
  },
  heroDesc: {
    textAlign: "left",
    // color: "#001524",
    fontSize: 24,
    fontFamily: "Raleway",
    paddingBottom: 28,
    width: 584,
  },
  contentHeader: {
    textAlign: "center",
    color: "#001524",
    fontSize: 35,
    fontFamily: "Raleway",
    fontWeight: "bolder",
    paddingTop: theme.spacing(5),
    backgroundColor: "#EEEEEE",
    margin: "0 !important",
  },
  contentFeatured: {
    gap: 15,
    // backgroundColor: "#2a344a",
    padding: theme.spacing(5),
    paddingTop: theme.spacing(4),
    paddingBottom: theme.spacing(7),
    backgroundColor: "#EEEEEE",
  },
  root: {
    flexGrow: 1,
  },
  searchs: {
    justifyContent: "left",
    display: "flex",
  },
  searchb: {
    backgroundColor: "white",
    height: "80%",
    width: "60%",
    padding: "15px",
    borderRadius: "10px",
    border: "1px solid #001524",
  },
  booksHeader: {
    textAlign: "center",
    color: "#001524",
    fontSize: 35,
    fontFamily: "Raleway",
    fontWeight: "bolder",
    paddingTop: theme.spacing(10),
  },
  booksDesc: {
    textAlign: "center",
    color: "#001524",
    fontSize: 20,
    paddingBottom: theme.spacing(2),
    fontFamily: "Raleway",
  },
}));
